### ISSUE TITLE
Menu item doesn't do anything

### ISSUE THREAD

**Issue by SXRWahrheit** [Logerfo/open-all-files#20]
I've clicked the open all files option a few times. It doesn't appear to do anything.

VS Code October 2019 (version 1.40)

**Comment by Logerfo** [comment]
I think the issue might be with VSCode. I filed an issue at microsoft/vscode#84688.

**Comment by Logerfo** [comment]
Fixed in [0.0.8](https://github.com/Logerfo/open-all-files/releases/tag/0.0.8). Thank you for reporting!
